### ISSUE TITLE
compression problem

### ISSUE THREAD

**Issue by shendayu** [MatejTymes/cassandra-zstd#1]
Hi, first of all, thanks for your code that gives great help!
I am using your cassandra-zstd in our cassandra for better compression ratio. but I found here was some problem, the debug info showed below. can you give me some help. our cassandra version is 3.0.8

DEBUG [MemtableFlushWriter:5] 2016-11-21 18:46:59,915 Memtable.java:353 - Writing Memtable-data_points@2066624083(40.813MiB serialized bytes, 31647 ops, 1%/8% of on/off-heap limit)
ERROR [MemtableFlushWriter:5] 2016-11-21 18:47:00,151 CassandraDaemon.java:201 - Exception in thread Thread[MemtableFlushWriter:5,5,RMI Runtime]
java.lang.AssertionError: null
        at org.apache.cassandra.db.ColumnIndex$Builder.close(ColumnIndex.java:174) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.db.ColumnIndex$Builder.build(ColumnIndex.java:114) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.db.ColumnIndex.writeAndBuildIndex(ColumnIndex.java:52) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.io.sstable.format.big.BigTableWriter.append(BigTableWriter.java:149) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.io.sstable.SimpleSSTableMultiWriter.append(SimpleSSTableMultiWriter.java:45) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.io.sstable.SSTableTxnWriter.append(SSTableTxnWriter.java:52) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.db.Memtable.writeSortedContents(Memtable.java:379) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.db.Memtable.flush(Memtable.java:326) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1071) ~[apache-cassandra-3.0.8.jar:3.0.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]

**Comment by MatejTymes** [comment]
Hi, thanks for your message. Do you by any chance have some pseudocode to reproduce this issue, or a description how you got to it?

**Comment by MatejTymes** [comment]
Fixed in 0.2.0

**Comment by MatejTymes** [comment]
Hi. Sorry for the inconvenience. Please update the version to 0.2.0 which contains the fix. It should be synced to maven repositories soon.

**Comment by shendayu** [comment]
thanks a lot, it works 👍
